name: foxer-client
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - master
    paths:
      - 'packages/foxer-client/**'
      - .github/workflows/foxer-client.yml
      - pnpm-lock.yaml
  pull_request:
    paths:
      - 'packages/foxer-client/**'
      - .github/workflows/foxer-client.yml
      - pnpm-lock.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm -r --filter foxer-client run lint
