name: foxer
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - master
    paths:
      - "packages/foxer/**"
      - .github/workflows/foxer.yml
      - bun.lock
  pull_request:
    paths:
      - "packages/foxer/**"
      - .github/workflows/foxer.yml
      - bun.lock
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: turbo build --filter @hugomrdias/foxer
      - run: turbo check --filter @hugomrdias/foxer
