name: Release
env:
  CI: true
  FORCE_COLOR: 1

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # needs to be personal token so release PRs can run workflows
          token: ${{ secrets.GH_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
  npm:
    needs: release
    if: ${{ needs.release.outputs.paths_released != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      RELEASE_PATH: ${{ fromJson(needs.release.outputs.paths_released)[0] }}
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org/"
      - run: bun install
      - run: bun run build
      - run: bun run check
      - run: bun publish
        working-directory: ${{ env.RELEASE_PATH }}
