name: Release
env:
  CI: true
  FORCE_COLOR: 1

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # needs to be personal token so release PRs can run workflows
          token: ${{ secrets.GH_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
  npm:
    needs: release
    if: |
      contains(fromJson(needs.release.outputs.paths_released), 'packages/foxer') ||
      contains(fromJson(needs.release.outputs.paths_released), 'packages/foxer-client') ||
      contains(fromJson(needs.release.outputs.paths_released), 'packages/foxer-react')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: turbo check
      - run: turbo publish --access=public
